package net.essence.client;

import net.essence.util.*;
import net.minecraft.client.renderer.entity.*;
import net.essence.entity.projectile.*;
import net.essence.client.render.mob.model.boil.*;
import net.minecraft.client.model.*;
import net.essence.entity.mob.boiling.*;
import net.essence.entity.mob.depths.*;
import net.essence.client.render.mob.model.depths.*;
import net.essence.entity.mob.euca.*;
import net.essence.client.render.mob.model.euca.*;
import net.essence.entity.mob.vanilla.*;
import net.essence.entity.*;
import net.essence.client.render.mob.model.vanilla.*;
import net.essence.client.render.mob.*;
import net.essence.entity.mob.boss.*;
import net.essence.client.render.mob.model.boss.*;
import net.minecraft.entity.player.*;
import net.essence.*;
import net.slayer.api.*;
import net.minecraftforge.client.*;
import net.essence.blocks.tileentity.*;
import net.essence.client.render.mob.model.statue.*;
import net.minecraft.client.renderer.tileentity.*;
import cpw.mods.fml.client.registry.*;
import net.essence.client.render.*;
import net.minecraft.util.*;

public class EntityRendering
{
    private static Textures tex;
    private static MobStats stat;
    
    public static void init() {
        final Class<EntityBasicProjectile> clazz = EntityBasicProjectile.class;
        final Textures tex = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz, (Render)new RenderStaffProjectile(Textures.basic, 1.0f, 0.2f, 0.2f));
        final Class<EntityDoomsBringer> clazz2 = EntityDoomsBringer.class;
        final Textures tex2 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz2, (Render)new RenderStaffProjectile(Textures.basic, 0.2f, 1.0f, 0.2f));
        final Class<EntityConjuring> clazz3 = EntityConjuring.class;
        final Textures tex3 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz3, (Render)new RenderStaffProjectile(Textures.basic, 0.1f, 1.0f, 0.7f));
        final Class<EntityEnlightment> clazz4 = EntityEnlightment.class;
        final Textures tex4 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz4, (Render)new RenderStaffProjectile(Textures.basic, 0.7f, 0.0f, 0.7f));
        final Class<EntityGreenpace> clazz5 = EntityGreenpace.class;
        final Textures tex5 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz5, (Render)new RenderStaffProjectile(Textures.basic, 0.6f, 1.0f, 0.0f));
        final Class<EntityWizardsStar> clazz6 = EntityWizardsStar.class;
        final Textures tex6 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz6, (Render)new RenderStaffProjectile(Textures.basic, 1.0f, 1.0f, 0.2f));
        final Class<EntityBouncingProjectile> clazz7 = EntityBouncingProjectile.class;
        final Textures tex7 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz7, (Render)new RenderProjectile(Textures.bouncingProjectile));
        final Class<EntityMagmaFireball> clazz8 = EntityMagmaFireball.class;
        final Textures tex8 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz8, (Render)new RenderProjectile(Textures.magmaBall));
        final Class<EntityRobot> clazz9 = EntityRobot.class;
        final ModelRobot model = new ModelRobot();
        final Textures tex9 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz9, (Render)new RenderModMob((ModelBase)model, Textures.robot));
        final Class<EntitySpikedBeast> clazz10 = EntitySpikedBeast.class;
        final ModelSpikedBeast model2 = new ModelSpikedBeast();
        final Textures tex10 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz10, (Render)new RenderModMob(model2, Textures.spikedBeast));
        RenderingRegistry.registerEntityRenderingHandler((Class)EntitySpyclops.class, (Render)new RenderSpyclops(new ModelSpyclops()));
        final Class<EntityMagmaGiant> clazz11 = EntityMagmaGiant.class;
        final ModelMagmaGiant model3 = new ModelMagmaGiant();
        final Textures tex11 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz11, (Render)new RenderModMob(model3, Textures.magmaGiant));
        RenderingRegistry.registerEntityRenderingHandler((Class)EntityInsecto.class, (Render)new RenderInsecto(new ModelInsecto()));
        RenderingRegistry.registerEntityRenderingHandler((Class)EntityPsyollom.class, (Render)new RenderPsyollom(new ModelPsyollom()));
        final Class<EntityDepthsBeast> clazz12 = EntityDepthsBeast.class;
        final ModelDepthsBeast model4 = new ModelDepthsBeast();
        final float shadow = 0.8f;
        final float size = 1.5f;
        final Textures tex12 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz12, (Render)new RenderSizeable(model4, shadow, size, Textures.depthsBeast));
        final Class<EntityDarknessCrawler> clazz13 = EntityDarknessCrawler.class;
        final ModelDarknessCrawler model5 = new ModelDarknessCrawler();
        final Textures tex13 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz13, (Render)new RenderModMob(model5, Textures.darknessCrawler));
        final Class<EntityBoom> clazz14 = EntityBoom.class;
        final ModelBoomBoom model6 = new ModelBoomBoom();
        final Textures tex14 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz14, (Render)new RenderBoomBoom(model6, Textures.boom));
        final Class<EntityBigHongo> clazz15 = EntityBigHongo.class;
        final ModelBigHongo model7 = new ModelBigHongo();
        final Textures tex15 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz15, (Render)new RenderModMob(model7, Textures.bigHongo));
        final Class<EntityMediumHongo> clazz16 = EntityMediumHongo.class;
        final ModelMediumHongo model8 = new ModelMediumHongo();
        final Textures tex16 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz16, (Render)new RenderModMob(model8, Textures.mediumHongo));
        final Class<EntitySmallHongo> clazz17 = EntitySmallHongo.class;
        final ModelSmallHongo model9 = new ModelSmallHongo();
        final Textures tex17 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz17, (Render)new RenderModMob(model9, Textures.smallHongo));
        RenderingRegistry.registerEntityRenderingHandler((Class)EntityEucaFighter.class, (Render)new RenderEucaFighter(new ModelEucaFighter()));
        final Class<EntityMagmaBlaze> clazz18 = EntityMagmaBlaze.class;
        final ModelBlaze model10 = new ModelBlaze();
        final Textures tex18 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz18, (Render)new RenderModMob((ModelBase)model10, Textures.magmaBlaze));
        final Class<EntityCrisp> clazz19 = EntityCrisp.class;
        final ModelDarknessCrawler model11 = new ModelDarknessCrawler();
        final Textures tex19 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz19, (Render)new RenderModMob(model11, Textures.crisp));
        final Class<EntityBurntMiner> clazz20 = EntityBurntMiner.class;
        final ModelBiped m = new ModelBiped();
        final Textures tex20 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz20, (Render)new RenderModBiped(m, Textures.burntMiner));
        final Class<EntityExposedFlame> clazz21 = EntityExposedFlame.class;
        final ModelBiped i = new ModelBiped();
        final Textures tex21 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz21, (Render)new RenderModBiped(i, Textures.exposedFlame));
        final Class<EntityBurningLight> clazz22 = EntityBurningLight.class;
        final ModelBiped j = new ModelBiped();
        final Textures tex22 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz22, (Render)new RenderModBiped(j, Textures.burningLight));
        final Class<EntityEucaHopper> clazz23 = EntityEucaHopper.class;
        final ModelEucaHopper par1ModelBase = new ModelEucaHopper();
        final Textures tex23 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz23, (Render)new RenderEucaHopper(par1ModelBase, Textures.eucaHopper));
        final Class<EntityAshHoarder> clazz24 = EntityAshHoarder.class;
        final ModelDepthsBeast model12 = new ModelDepthsBeast();
        final float shadow2 = 0.8f;
        final float size2 = 1.5f;
        final Textures tex24 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz24, (Render)new RenderSizeable(model12, shadow2, size2, Textures.ashHoarder));
        final Class<EntityBurntAsh> clazz25 = EntityBurntAsh.class;
        final ModelPsyollom model13 = new ModelPsyollom();
        final float shadow3 = 0.5f;
        final float size3 = 1.5f;
        final Textures tex25 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz25, (Render)new RenderSizeable(model13, shadow3, size3, Textures.burntAsh));
        final Class<EntityReaper> clazz26 = EntityReaper.class;
        final ModelReaper model14 = new ModelReaper();
        final Textures tex26 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz26, (Render)new RenderReaper(model14, Textures.reaper));
        final Class<EntityDepthsHunter> clazz27 = EntityDepthsHunter.class;
        final ModelDepthsHunter model15 = new ModelDepthsHunter();
        final float shadow4 = 0.5f;
        final float size4 = 1.5f;
        final Textures tex27 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz27, (Render)new RenderSizeable(model15, shadow4, size4, Textures.depthsHunter));
        final Class<EntityEucaCharger> clazz28 = EntityEucaCharger.class;
        final ModelEucaCharger model16 = new ModelEucaCharger();
        final float shadow5 = 0.5f;
        final float size5 = 1.5f;
        final Textures tex28 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz28, (Render)new RenderSizeable(model16, shadow5, size5, Textures.eucaCharger));
        final Class<EntityBunny> clazz29 = EntityBunny.class;
        final ModelBunny model17 = new ModelBunny();
        final float shadow6 = 0.3f;
        final Textures tex29 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz29, (Render)new RenderModMob(model17, shadow6, Textures.bunny));
        final Class<EntitySandCrawler> clazz30 = EntitySandCrawler.class;
        final ModelSandCrawler model18 = new ModelSandCrawler();
        final float shadow7 = 0.5f;
        final Textures tex30 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz30, (Render)new RenderModMob(model18, shadow7, Textures.sandCrawler));
        final Class<EntityTurtle> clazz31 = EntityTurtle.class;
        final ModelTurtle model19 = new ModelTurtle();
        final float shadow8 = 0.5f;
        final Textures tex31 = EntityRendering.tex;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz31, (Render)new RenderModMob(model19, shadow8, Textures.turtle));
        RenderingRegistry.registerEntityRenderingHandler((Class)EntityFish.class, (Render)new RenderFish(new ModelFish()));
        RenderingRegistry.registerEntityRenderingHandler((Class)EntityDragonEgg.class, (Render)new RenderDragonEgg(new ModelDragonEgg()));
        final Class<EntityNetherBeast> clazz32 = EntityNetherBeast.class;
        final ModelBeastOfTheNether model20 = new ModelBeastOfTheNether();
        final float shadow9 = 0.5f;
        final float size6 = 2.0f;
        final Textures tex32 = EntityRendering.tex;
        final ResourceLocation netherBeast = Textures.netherBeast;
        final MobStats stat = EntityRendering.stat;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz32, (Render)new RenderBoss(model20, shadow9, size6, netherBeast, 1));
        final Class<EntityWitheringBeast> clazz33 = EntityWitheringBeast.class;
        final ModelWitheringBeast model21 = new ModelWitheringBeast();
        final float shadow10 = 0.5f;
        final float size7 = 2.0f;
        final Textures tex33 = EntityRendering.tex;
        final ResourceLocation witheringBeast = Textures.witheringBeast;
        final MobStats stat2 = EntityRendering.stat;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz33, (Render)new RenderBoss(model21, shadow10, size7, witheringBeast, 0));
        final Class<EntityCalcia> clazz34 = EntityCalcia.class;
        final ModelClacia model22 = new ModelClacia();
        final float shadow11 = 0.5f;
        final float size8 = 2.0f;
        final Textures tex34 = EntityRendering.tex;
        final ResourceLocation calcia = Textures.calcia;
        final MobStats stat3 = EntityRendering.stat;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz34, (Render)new RenderCalcia(model22, shadow11, size8, calcia, 2));
        final Class<EntityEudor> clazz35 = EntityEudor.class;
        final ModelEudor model23 = new ModelEudor();
        final float shadow12 = 0.5f;
        final float size9 = 2.0f;
        final Textures tex35 = EntityRendering.tex;
        final ResourceLocation eudor = Textures.eudor;
        final MobStats stat4 = EntityRendering.stat;
        RenderingRegistry.registerEntityRenderingHandler((Class)clazz35, (Render)new RenderBoss(model23, shadow12, size9, eudor, 4));
        RenderingRegistry.registerEntityRenderingHandler((Class)EntityPlayer.class, (Render)new RenderCloakedPlayer());
        SlayerAPI.registerItemRenderer(EssenceBlocks.netherBeastStatue, (IItemRenderer)new ItemRendererStatue("netherBeastStatue"));
        SlayerAPI.registerItemRenderer(EssenceBlocks.witheringBeastStatue, (IItemRenderer)new ItemRendererStatue("witheringBeastStatue"));
        SlayerAPI.registerItemRenderer(EssenceBlocks.calciaStatue, (IItemRenderer)new ItemRendererStatue("calciaStatue"));
        SlayerAPI.registerItemRenderer(EssenceBlocks.eudorStatue, (IItemRenderer)new ItemRendererStatue("eudorStatue"));
        ClientRegistry.bindTileEntitySpecialRenderer((Class)TileEntityStatue.class, (TileEntitySpecialRenderer)new StatueRenderer());
        RenderingRegistry.registerBlockHandler(EssenceBlocks.celestiumOre.getRenderType(), (ISimpleBlockRenderingHandler)new OreRenderer());
        RenderingRegistry.registerBlockHandler(EssenceBlocks.mossyEssenceStone.getRenderType(), (ISimpleBlockRenderingHandler)new OtherBlockRenderer());
    }
}
