package net.essence;

import net.minecraft.item.*;
import net.minecraftforge.common.util.*;
import net.essence.util.*;
import net.essence.entity.projectile.*;
import net.minecraft.potion.*;
import net.slayer.api.item.*;
import net.essence.items.*;

public class EssenceItems
{
    public static Item.ToolMaterial hellstoneSwordMat;
    public static Item.ToolMaterial flairiumSwordMat;
    public static Item.ToolMaterial celestiumSwordMat;
    public static Item.ToolMaterial shadiumSwordMat;
    public static Item.ToolMaterial luniumSwordMat;
    public static Item.ToolMaterial sapphiretoolSwordMat;
    public static Item.ToolMaterial hellstone;
    public static Item.ToolMaterial flairium;
    public static Item.ToolMaterial lunium;
    public static Item.ToolMaterial celestium;
    public static Item.ToolMaterial shadium;
    public static Item.ToolMaterial sapphiretool;
    public static Item.ToolMaterial hellstoneMulti;
    public static Item.ToolMaterial flairiumMulti;
    public static Item.ToolMaterial luniumMulti;
    public static Item.ToolMaterial celestiumMulti;
    public static Item.ToolMaterial shadiumMulti;
    public static Item.ToolMaterial sapphireMulti;
    public static int HEAD;
    public static int BODY;
    public static int LEGS;
    public static int BOOTS;
    public static final Item hellstoneIngot;
    public static final Item shadiumIngot;
    public static final Item celestiumIngot;
    public static final Item luniumIngot;
    public static final Item flairiumIngot;
    public static final Item ash;
    public static final Item sapphire;
    public static final Item hellstoneClump;
    public static final Item shadiumClump;
    public static final Item luniumClump;
    public static final Item spawnerClump;
    public static final Item spawnerBar;
    public static final Item flameCoin;
    public static final Item chaosCannon;
    public static final Item hellstoneMultiTool;
    public static final Item shadiumMultiTool;
    public static final Item celestiumMultiTool;
    public static final Item luniumMultiTool;
    public static final Item flairiumMultiTool;
    public static final Item sapphireMultiTool;
    public static final Item hellstonePickaxe;
    public static final Item shadiumPickaxe;
    public static final Item celestiumPickaxe;
    public static final Item luniumPickaxe;
    public static final Item flairiumPickaxe;
    public static final Item sapphirePickaxe;
    public static final Item hellstoneShovel;
    public static final Item shadiumShovel;
    public static final Item celestiumShovel;
    public static final Item luniumShovel;
    public static final Item flairiumShovel;
    public static final Item sapphireShovel;
    public static final Item hellstoneAxe;
    public static final Item shadiumAxe;
    public static final Item celestiumAxe;
    public static final Item luniumAxe;
    public static final Item flairiumAxe;
    public static final Item sapphireAxe;
    public static final Item hellstoneHoe;
    public static final Item shadiumHoe;
    public static final Item celestiumHoe;
    public static final Item luniumHoe;
    public static final Item flairiumHoe;
    public static final Item sapphireHoe;
    public static final Item hellstoneSword;
    public static final Item shadiumSword;
    public static final Item celestiumSword;
    public static final Item luniumSword;
    public static final Item flairiumSword;
    public static final Item sapphireSword;
    public static final Item poisonSword;
    public static final Item cloudSlicer;
    public static final Item dragonsTooth;
    public static final Item netherBeastSword;
    public static final Item witheringBeastSword;
    public static final Item calciaSword;
    public static final Item championsSword;
    public static final Item theWraith;
    public static final Item eucaPortalGem;
    public static final Item depthsPortalGem;
    public static final Item calciaOrb;
    public static final Item netherBeastOrb;
    public static final Item witheringBeastOrb;
    public static final Item weakDarkEnergyPotion;
    public static final Item strongDarkEnergyPotion;
    public static final Item weakEssencePotion;
    public static final Item strongEssencePotion;
    public static final Item hellstoneHelmet;
    public static final Item hellstoneChest;
    public static final Item hellstoneLegs;
    public static final Item hellstoneBoots;
    public static final Item flairiumHelmet;
    public static final Item flairiumChest;
    public static final Item flairiumLegs;
    public static final Item flairiumBoots;
    public static final Item celestiumHelmet;
    public static final Item celestiumChest;
    public static final Item celestiumLegs;
    public static final Item celestiumBoots;
    public static final Item luniumHelmet;
    public static final Item luniumChest;
    public static final Item luniumLegs;
    public static final Item luniumBoots;
    public static final Item shadiumHelmet;
    public static final Item shadiumChest;
    public static final Item shadiumLegs;
    public static final Item shadiumBoots;
    public static final Item condensedDiamondHelmet;
    public static final Item condensedDiamondChest;
    public static final Item condensedDiamondLegs;
    public static final Item condensedDiamondBoots;
    public static final Item sapphireHelmet;
    public static final Item sapphireChest;
    public static final Item sapphireLegs;
    public static final Item sapphireBoots;
    public static final Item backBiter;
    public static final Item dawnBreaker;
    public static final Item tempestBattleaxe;
    public static final Item staffOfHellstone;
    public static final Item doomsBringer;
    public static final Item conjuringStaff;
    public static final Item staffOfEnlightment;
    public static final Item staffOfGreenpace;
    public static final Item wizardsStar;
    public static final Item teleportationStaff;
    public static final Item goldenSteak;
    public static final Item goldenSteakOP;
    public static final Item goldenPotato;
    public static final Item goldenPotatoOP;
    public static final Item goldenPork;
    public static final Item goldenPorkOP;
    public static final Item eucaMeat;
    public static final ItemModDoor hotDoorItem;
    public static final Item spawners;
    
    public static Item.ToolMaterial addToolMaterial(final int uses, final float efficiency, final float dam, final boolean breakable) {
        return EnumHelper.addToolMaterial("tool", 3, breakable ? uses : -1, efficiency, dam, 30);
    }
    
    static {
        EssenceItems.hellstoneSwordMat = addToolMaterial(2356, 13.0f, 10.0f, true);
        EssenceItems.flairiumSwordMat = addToolMaterial(3120, 13.0f, 25.0f, true);
        EssenceItems.celestiumSwordMat = addToolMaterial(3120, 13.0f, 20.0f, true);
        EssenceItems.shadiumSwordMat = addToolMaterial(2210, 13.0f, 8.0f, true);
        EssenceItems.luniumSwordMat = addToolMaterial(2210, 13.0f, 8.0f, true);
        EssenceItems.sapphiretoolSwordMat = addToolMaterial(1561, 13.0f, 7.0f, true);
        EssenceItems.hellstone = addToolMaterial(1600, 10.0f, 5.0f, true);
        EssenceItems.flairium = addToolMaterial(3000, 15.0f, 5.0f, true);
        EssenceItems.lunium = addToolMaterial(3000, 9.0f, 5.0f, true);
        EssenceItems.celestium = addToolMaterial(1600, 13.0f, 5.0f, true);
        EssenceItems.shadium = addToolMaterial(1600, 10.0f, 5.0f, true);
        EssenceItems.sapphiretool = addToolMaterial(1561, 8.0f, 5.0f, true);
        EssenceItems.hellstoneMulti = addToolMaterial(3000, 12.0f, 5.0f, false);
        EssenceItems.flairiumMulti = addToolMaterial(3000, 15.0f, 5.0f, false);
        EssenceItems.luniumMulti = addToolMaterial(3000, 9.0f, 5.0f, false);
        EssenceItems.celestiumMulti = addToolMaterial(3000, 13.0f, 5.0f, false);
        EssenceItems.shadiumMulti = addToolMaterial(3000, 10.0f, 5.0f, false);
        EssenceItems.sapphireMulti = addToolMaterial(3000, 8.0f, 5.0f, false);
        EssenceItems.HEAD = 0;
        EssenceItems.BODY = 1;
        EssenceItems.LEGS = 2;
        EssenceItems.BOOTS = 3;
        hellstoneIngot = new ItemMod("hellstoneIngot");
        shadiumIngot = new ItemMod("shadiumIngot");
        celestiumIngot = new ItemMod("celestiumIngot");
        luniumIngot = new ItemMod("luniumIngot");
        flairiumIngot = new ItemMod("flairiumIngot");
        ash = new ItemMod("ash");
        sapphire = new ItemMod("sapphire");
        hellstoneClump = new ItemMod("hellstoneClump");
        shadiumClump = new ItemMod("shadiumClump");
        luniumClump = new ItemMod("luniumClump");
        spawnerClump = new ItemMod("spawnerClump");
        spawnerBar = new ItemMod("spawnerBar");
        flameCoin = new ItemFlameCoin("flameCoin");
        chaosCannon = new ItemChaosCannon("chaosCannon");
        hellstoneMultiTool = (Item)new ItemMultiTool("hellstoneMultiTool", EssenceToolMaterial.HELLSTONE_MULTI_TOOL);
        shadiumMultiTool = (Item)new ItemMultiTool("shadiumMultiTool", EssenceToolMaterial.SHADIUM_MULTI_TOOL);
        celestiumMultiTool = (Item)new ItemMultiTool("celestiumMultiTool", EssenceToolMaterial.CELESTIUM_MULTI_TOOL);
        luniumMultiTool = (Item)new ItemMultiTool("luniumMultiTool", EssenceToolMaterial.LUNIUM_MULTI_TOOL);
        flairiumMultiTool = (Item)new ItemMultiTool("flairiumMultiTool", EssenceToolMaterial.FLAIRIUM_MULTI_TOOL);
        sapphireMultiTool = (Item)new ItemMultiTool("sapphireMultiTool", EssenceToolMaterial.SAPPHIRE_MULTI_TOOL);
        hellstonePickaxe = (Item)new ItemModPickaxe("hellstonePickaxe", EssenceToolMaterial.HELLSTONE_PICKAXE);
        shadiumPickaxe = (Item)new ItemModPickaxe("shadiumPickaxe", EssenceToolMaterial.SHADIUM_PICKAXE);
        celestiumPickaxe = (Item)new ItemModPickaxe("celestiumPickaxe", EssenceToolMaterial.CELESTIUM_PICKAXE);
        luniumPickaxe = (Item)new ItemModPickaxe("luniumPickaxe", EssenceToolMaterial.LUNIUM_PICKAXE);
        flairiumPickaxe = (Item)new ItemModPickaxe("flairiumPickaxe", EssenceToolMaterial.FLAIRIUM_PICKAXE);
        sapphirePickaxe = (Item)new ItemModPickaxe("sapphirePickaxe", EssenceToolMaterial.SAPPHIRE_PICKAXE);
        hellstoneShovel = (Item)new ItemModShovel("hellstoneShovel", EssenceToolMaterial.HELLSTONE_SHOVEL);
        shadiumShovel = (Item)new ItemModShovel("shadiumShovel", EssenceToolMaterial.SHADIUM_SHOVEL);
        celestiumShovel = (Item)new ItemModShovel("celestiumShovel", EssenceToolMaterial.CELESTIUM_SHOVEL);
        luniumShovel = (Item)new ItemModShovel("luniumShovel", EssenceToolMaterial.LUNIUM_SHOVEL);
        flairiumShovel = (Item)new ItemModShovel("flairiumShovel", EssenceToolMaterial.FLAIRIUM_SHOVEL);
        sapphireShovel = (Item)new ItemModShovel("sapphireShovel", EssenceToolMaterial.SAPPHIRE_SHOVEL);
        hellstoneAxe = (Item)new ItemModAxe("hellstoneAxe", EssenceToolMaterial.HELLSTONE_AXE);
        shadiumAxe = (Item)new ItemModAxe("shadiumAxe", EssenceToolMaterial.SHADIUM_AXE);
        celestiumAxe = (Item)new ItemModAxe("celestiumAxe", EssenceToolMaterial.CELESTIUM_AXE);
        luniumAxe = (Item)new ItemModAxe("luniumAxe", EssenceToolMaterial.LUNIUM_AXE);
        flairiumAxe = (Item)new ItemModAxe("flairiumAxe", EssenceToolMaterial.FLAIRIUM_AXE);
        sapphireAxe = (Item)new ItemModAxe("sapphireAxe", EssenceToolMaterial.SAPPHIRE_AXE);
        hellstoneHoe = (Item)new ItemModHoe("hellstoneHoe", EssenceToolMaterial.HELLSTONE_HOE);
        shadiumHoe = (Item)new ItemModHoe("shadiumHoe", EssenceToolMaterial.SHADIUM_HOE);
        celestiumHoe = (Item)new ItemModHoe("celestiumHoe", EssenceToolMaterial.CELESTIUM_HOE);
        luniumHoe = (Item)new ItemModHoe("luniumHoe", EssenceToolMaterial.LUNIUM_HOE);
        flairiumHoe = (Item)new ItemModHoe("flairiumHoe", EssenceToolMaterial.FLAIRIUM_HOE);
        sapphireHoe = (Item)new ItemModHoe("sapphireHoe", EssenceToolMaterial.SAPPHIRE_HOE);
        hellstoneSword = (Item)new ItemFireSword("hellstoneSword", EssenceToolMaterial.HELLSTONE_SWORD);
        shadiumSword = (Item)new ItemFreezeSword("shadiumSword", EssenceToolMaterial.SHADIUM_SWORD);
        celestiumSword = (Item)new ItemModSword("celestiumSword", EssenceToolMaterial.CELESTIUM_SWORD);
        luniumSword = (Item)new ItemModSword("luniumSword", EssenceToolMaterial.LUNIUM_SWORD);
        flairiumSword = (Item)new ItemFireSword("flairiumSword", EssenceToolMaterial.FLAIRIUM_SWORD);
        sapphireSword = (Item)new ItemModSword("sapphireSword", EssenceToolMaterial.SAPPHIRE_SWORD);
        poisonSword = (Item)new ItemPoisionSword("poisonSword", EssenceToolMaterial.POISON_SWORD);
        cloudSlicer = (Item)new ItemModSword("cloudSlicer", EssenceToolMaterial.CLOUD_SLICER);
        dragonsTooth = (Item)new ItemModSword("dragonsTooth", EssenceToolMaterial.DRAGONS_TOOTH);
        netherBeastSword = (Item)new ItemModSword("netherBeastSword", EssenceToolMaterial.NETHER_BEAST_SWORD);
        witheringBeastSword = (Item)new ItemWitherSword("witheringBeastSword", EssenceToolMaterial.WITHERING_BEAST_SWORD);
        calciaSword = (Item)new ItemModSword("calciaSword", EssenceToolMaterial.CALCIA_SWORD);
        championsSword = (Item)new ItemModSword("championsSword", EssenceToolMaterial.CHAMPIONS_SWORD);
        theWraith = (Item)new ItemModSword("theWraith", EssenceToolMaterial.THE_WRAITH);
        eucaPortalGem = new ItemMod("eucaPortalGem");
        depthsPortalGem = new ItemMod("depthsPortalGem");
        calciaOrb = new ItemNetherBossSpawner("calciaOrb");
        netherBeastOrb = new ItemNetherBossSpawner("netherBeastOrb");
        witheringBeastOrb = new ItemNetherBossSpawner("witheringBeastOrb");
        weakDarkEnergyPotion = new ItemEssencePotion("weakDarkEnergyPotion", false, false);
        strongDarkEnergyPotion = new ItemEssencePotion("strongDarkEnergyPotion", true, false);
        weakEssencePotion = new ItemEssencePotion("weakEssencePotion", false, true);
        strongEssencePotion = new ItemEssencePotion("strongEssencePotion", true, true);
        hellstoneHelmet = (Item)new ItemModArmor(EnumArmor.HELLSTONE, EssenceItems.HEAD);
        hellstoneChest = (Item)new ItemModArmor(EnumArmor.HELLSTONE, EssenceItems.BODY);
        hellstoneLegs = (Item)new ItemModArmor(EnumArmor.HELLSTONE, EssenceItems.LEGS);
        hellstoneBoots = (Item)new ItemModArmor(EnumArmor.HELLSTONE, EssenceItems.BOOTS);
        flairiumHelmet = (Item)new ItemModArmor(EnumArmor.FLAIRIUM, EssenceItems.HEAD);
        flairiumChest = (Item)new ItemModArmor(EnumArmor.FLAIRIUM, EssenceItems.BODY);
        flairiumLegs = (Item)new ItemModArmor(EnumArmor.FLAIRIUM, EssenceItems.LEGS);
        flairiumBoots = (Item)new ItemModArmor(EnumArmor.FLAIRIUM, EssenceItems.BOOTS);
        celestiumHelmet = (Item)new ItemModArmor(EnumArmor.CELESTIUM, EssenceItems.HEAD);
        celestiumChest = (Item)new ItemModArmor(EnumArmor.CELESTIUM, EssenceItems.BODY);
        celestiumLegs = (Item)new ItemModArmor(EnumArmor.CELESTIUM, EssenceItems.LEGS);
        celestiumBoots = (Item)new ItemModArmor(EnumArmor.CELESTIUM, EssenceItems.BOOTS);
        luniumHelmet = (Item)new ItemModArmor(EnumArmor.LUNIUM, EssenceItems.HEAD);
        luniumChest = (Item)new ItemModArmor(EnumArmor.LUNIUM, EssenceItems.BODY);
        luniumLegs = (Item)new ItemModArmor(EnumArmor.LUNIUM, EssenceItems.LEGS);
        luniumBoots = (Item)new ItemModArmor(EnumArmor.LUNIUM, EssenceItems.BOOTS);
        shadiumHelmet = (Item)new ItemModArmor(EnumArmor.SHADIUM, EssenceItems.HEAD);
        shadiumChest = (Item)new ItemModArmor(EnumArmor.SHADIUM, EssenceItems.BODY);
        shadiumLegs = (Item)new ItemModArmor(EnumArmor.SHADIUM, EssenceItems.LEGS);
        shadiumBoots = (Item)new ItemModArmor(EnumArmor.SHADIUM, EssenceItems.BOOTS);
        condensedDiamondHelmet = (Item)new ItemModArmor(EnumArmor.CONDENSED_DIAMOND, EssenceItems.HEAD);
        condensedDiamondChest = (Item)new ItemModArmor(EnumArmor.CONDENSED_DIAMOND, EssenceItems.BODY);
        condensedDiamondLegs = (Item)new ItemModArmor(EnumArmor.CONDENSED_DIAMOND, EssenceItems.LEGS);
        condensedDiamondBoots = (Item)new ItemModArmor(EnumArmor.CONDENSED_DIAMOND, EssenceItems.BOOTS);
        sapphireHelmet = (Item)new ItemModArmor(EnumArmor.SAPPHIRE, EssenceItems.HEAD);
        sapphireChest = (Item)new ItemModArmor(EnumArmor.SAPPHIRE, EssenceItems.BODY);
        sapphireLegs = (Item)new ItemModArmor(EnumArmor.SAPPHIRE, EssenceItems.LEGS);
        sapphireBoots = (Item)new ItemModArmor(EnumArmor.SAPPHIRE, EssenceItems.BOOTS);
        backBiter = (Item)new ItemBattleAxe("backBiter", EssenceToolMaterial.BACK_BITER);
        dawnBreaker = (Item)new ItemBattleAxe("dawnBreaker", EssenceToolMaterial.DAWN_BREAKER);
        tempestBattleaxe = (Item)new ItemBattleAxe("tempestBattleaxe", EssenceToolMaterial.TEMPEST_BATTLEAXE);
        staffOfHellstone = new ItemStaff("staffOfHellstone", 25, 1000, 10, false, false, EntityBasicProjectile.class);
        doomsBringer = new ItemStaff("doomsBringer", 25, 1000, 10, false, false, (Class<? extends EntityBasicProjectile>)EntityDoomsBringer.class);
        conjuringStaff = new ItemStaff("conjuringStaff", 25, 1000, 10, true, false, (Class<? extends EntityBasicProjectile>)EntityConjuring.class);
        staffOfEnlightment = new ItemStaff("staffOfEnlightment", 25, 1000, 10, true, false, (Class<? extends EntityBasicProjectile>)EntityEnlightment.class);
        staffOfGreenpace = new ItemStaff("staffOfGreenpace", 25, 1000, 10, true, false, (Class<? extends EntityBasicProjectile>)EntityGreenpace.class);
        wizardsStar = new ItemStaff("wizardsStar", 25, 1000, 10, true, false, (Class<? extends EntityBasicProjectile>)EntityWizardsStar.class);
        teleportationStaff = new ItemTeleport("teleportationStaff", 20);
        goldenSteak = (Item)new ItemGoldenFood("normalGoldenSteak", "goldenSteak", "Golden Steak", 4, 1.2f, false, false).setPotionEffect(Potion.regeneration.id, 5, 1, 1.0f).setAlwaysEdible();
        goldenSteakOP = (Item)new ItemGoldenFood("OPGoldenSteak", "goldenSteak", "Golden Steak", 4, 1.2f, false, true).setPotionEffect(Potion.regeneration.id, 5, 1, 1.0f).setAlwaysEdible();
        goldenPotato = (Item)new ItemGoldenFood("normalGoldenPotato", "goldenPotato", "Golden Potato", 4, 1.2f, false, false).setPotionEffect(Potion.regeneration.id, 5, 1, 1.0f).setAlwaysEdible();
        goldenPotatoOP = (Item)new ItemGoldenFood("OPGoldenPotato", "goldenPotato", "Golden Potato", 4, 1.2f, false, true).setPotionEffect(Potion.regeneration.id, 5, 1, 1.0f).setAlwaysEdible();
        goldenPork = (Item)new ItemGoldenFood("normalGoldenPork", "goldenPorkchop", "Golden Porkchop", 4, 1.2f, false, false).setPotionEffect(Potion.regeneration.id, 5, 1, 1.0f).setAlwaysEdible();
        goldenPorkOP = (Item)new ItemGoldenFood("OPGoldenPork", "goldenPorkchop", "Golden Porkchop", 4, 1.2f, false, true).setPotionEffect(Potion.regeneration.id, 5, 1, 1.0f).setAlwaysEdible();
        eucaMeat = (Item)new ItemModFood("eucaMeat", 6, 0.6f, 10, false);
        hotDoorItem = new ItemModDoor(EssenceBlocks.hotDoor, "hotDoor");
        spawners = new ItemSpawnEggs();
    }
}
