package net.essence;

import net.minecraft.block.*;
import net.minecraft.creativetab.*;
import net.slayer.api.*;
import net.essence.client.*;
import net.essence.client.render.mob.model.statue.*;
import net.minecraft.item.*;
import net.essence.blocks.*;
import net.slayer.api.block.*;

public class EssenceBlocks
{
    public static final Block hellstoneOre;
    public static final Block celestiumOre;
    public static final Block luniumOre;
    public static final Block shadiumOre;
    public static final Block flairiumOre;
    public static final Block ashual;
    public static final Block sapphireOre;
    public static final Block hellstoneBlock;
    public static final Block celestiumBlock;
    public static final Block luniumBlock;
    public static final Block shadiumBlock;
    public static final Block flairiumBlock;
    public static final Block sapphireBlock;
    public static final Block hellstoneBlockOverlay;
    public static final Block celestiumBlockOverlay;
    public static final Block luniumBlockOverlay;
    public static final Block shadiumBlockOverlay;
    public static final Block flairiumBlockOverlay;
    public static final Block halfSlab;
    public static final Block fullSlab;
    public static final BlockMod eucaDirt;
    public static final Block eucaGrass;
    public static final Block eucaStone;
    public static final Block eucaLog;
    public static final Block eucaPlank;
    public static final Block eucaStairs;
    public static final Block redEucaLeaves;
    public static final Block greenEucaLeaves;
    public static final Block blueEucaLeaves;
    public static final Block eucaSapling;
    public static final BlockMod depthsDirt;
    public static final Block depthsGrass;
    public static final Block depthsStone;
    public static final Block depthsLog;
    public static final Block depthsPlank;
    public static final Block depthsStairs;
    public static final Block depthsLeaves;
    public static final BlockMod godDirt;
    public static final Block godGrass;
    public static final Block godStone;
    public static final BlockMod frozenDirt;
    public static final Block frozenGrass;
    public static final Block frozenStone;
    public static final BlockEucaPortal eucaPortal;
    public static final Block eucaPortalFrame;
    public static final BlockDepthsPortal depthsPortal;
    public static final Block depthsPortalFrame;
    public static final BlockBoilPortal boilPortal;
    public static final Block boilPortalFrame;
    public static final BlockFrozenPortal frozenPortal;
    public static final Block hotBlock;
    public static final Block ashBlock;
    public static final Block fire;
    public static final Block boilingFire;
    public static final Block mossyEssenceStone;
    public static final Block dungeonBrick;
    public static final Block dungeonCrackedBrick;
    public static final Block dungeonChisledBrick;
    public static final Block dungeonBrickCarved;
    public static final Block dungeonLamp;
    public static final Block dungeonBrickStairs;
    public static final Block dungeonCrackedBrickStairs;
    public static final Block dungeonChisledBrickStairs;
    public static final Block dungeonBrickCarvedStairs;
    public static final Block dungeonLampStairs;
    public static final Block dungeonBrickFence;
    public static final Block dungeonCrackedBrickFence;
    public static final Block dungeonChisledBrickFence;
    public static final Block dungeonBrickCarvedFence;
    public static final Block dungeonLampFence;
    public static final Block hotBrick;
    public static final Block hotBrick_fence;
    public static final Block hotBrick_stairs;
    public static final Block hotGlass;
    public static final Block smoothGlass;
    public static final Block hotGlassPane;
    public static final Block smoothGlassPane;
    public static final Block witheringBeastStatue;
    public static final Block netherBeastStatue;
    public static final Block calciaStatue;
    public static final Block eudorStatue;
    public static final Block enrichedEnchantmentTable;
    public static final BlockModDoor hotDoor;
    public static final Block colouredBricks;
    public static final Block miniColouredBricks;
    public static final Block glowshroom;
    public static final Block caveVine;
    public static final Block storageBlocks;
    public static final Block storageBlocks1;
    public static final Block storageBlocks2;
    public static final Block storageBlocks3;
    public static final Block christmasLights;
    public static final Block workshopCarpet;
    public static final Block frozenGlass;
    public static final Block frozenPane;
    public static final Block workshopLamp;
    public static final Block workshopStone;
    public static final Block workshopStoneStair;
    public static final Block workshopStoneFence;
    public static final BlockModDoor frozenDoor;
    public static final Block candyCane;
    public static final Block workshopSlab;
    public static final Block eucaTallGrass;
    public static final Block eucaGreenFlower;
    public static final Block eucaBlueFlower;

    static {
        hellstoneOre = new BlockModOre("hellstoneOre", 3.0f).setHarvestLevel(EnumToolType.DIAMOND_PICK);
        celestiumOre = new BlockModOre("celestiumOre", 2.0f).setHarvestLevel(EnumToolType.DIAMOND_PICK);
        luniumOre = new BlockModOre("luniumOre", 2.0f).setHarvestLevel(EnumToolType.DIAMOND_PICK);
        shadiumOre = new BlockModOre("shadiumOre", 2.0f).setHarvestLevel(EnumToolType.DIAMOND_PICK);
        flairiumOre = new BlockModOre("flairiumOre", 2.0f).setHarvestLevel(EnumToolType.DIAMOND_PICK);
        ashual = (Block)new BlockModOre("ashual", 2.0f);
        sapphireOre = new BlockModOre("sapphireOre", 2.0f).setHarvestLevel(EnumToolType.IRON_PICK);
        hellstoneBlock = new BlockModOre("hellstoneBlock", 3.0f).setHarvestLevel(EnumToolType.IRON_PICK);
        celestiumBlock = new BlockModOre("celestiumBlock", 2.0f).setHarvestLevel(EnumToolType.IRON_PICK);
        luniumBlock = new BlockModOre("luniumBlock", 2.0f).setHarvestLevel(EnumToolType.IRON_PICK);
        shadiumBlock = new BlockModOre("shadiumBlock", 2.0f).setHarvestLevel(EnumToolType.IRON_PICK);
        flairiumBlock = new BlockModOre("flairiumBlock", 2.0f).setHarvestLevel(EnumToolType.IRON_PICK);
        sapphireBlock = new BlockModOre("sapphireBlock", 2.0f).setHarvestLevel(EnumToolType.IRON_PICK);
        hellstoneBlockOverlay = new BlockModOre("hellstoneBlock_overlay", -1.0f).setCreativeTab((CreativeTabs)null);
        celestiumBlockOverlay = new BlockModOre("celestiumBlock_overlay", -1.0f).setCreativeTab((CreativeTabs)null);
        luniumBlockOverlay = new BlockModOre("luniumBlock_overlay", -1.0f).setCreativeTab((CreativeTabs)null);
        shadiumBlockOverlay = new BlockModOre("shadiumBlock_overlay", -1.0f).setCreativeTab((CreativeTabs)null);
        flairiumBlockOverlay = new BlockModOre("flairiumBlock_overlay", -1.0f).setCreativeTab((CreativeTabs)null);
        halfSlab = (Block)new BlockModSlab(false);
        fullSlab = (Block)new BlockModSlab(true);
        eucaDirt = new BlockMod(EnumMaterialTypes.DIRT, "eucaDirt", 2.0f);
        eucaGrass = new BlockModGrass(EssenceBlocks.eucaDirt, "eucaGrass", 2.0f, "eucaDirt");
        eucaStone = new BlockMod("eucaStone", 2.0f);
        eucaLog = (Block)new BlockModLog("eucaLog");
        eucaPlank = new BlockMod(EnumMaterialTypes.WOOD, "eucaPlank", 1.0f);
        eucaStairs = (Block)new BlockModStairs(EssenceBlocks.eucaPlank, "eucaStairs");
        redEucaLeaves = new BlockModLeaves("redEucaLeaves", 1.0f);
        greenEucaLeaves = new BlockModLeaves("greenEucaLeaves", 1.0f);
        blueEucaLeaves = new BlockModLeaves("blueEucaLeaves", 1.0f);
        eucaSapling = (Block)new BlockEucaSapling("eucaSapling");
        depthsDirt = new BlockMod(EnumMaterialTypes.DIRT, "depthsDirt", 2.0f);
        depthsGrass = new BlockModGrass(EssenceBlocks.depthsDirt, "depthsGrass", 2.0f, "depthsDirt");
        depthsStone = new BlockMod("depthsStone", 2.0f);
        depthsLog = (Block)new BlockModLog("depthsLog");
        depthsPlank = new BlockMod(EnumMaterialTypes.WOOD, "depthsPlank", 1.0f);
        depthsStairs = (Block)new BlockModStairs(EssenceBlocks.depthsPlank, "depthsStairs");
        depthsLeaves = new BlockModLeaves("depthsLeaves", 1.0f);
        godDirt = new BlockMod(EnumMaterialTypes.DIRT, "godDirt", 2.0f);
        godGrass = new BlockModGrass(EssenceBlocks.godDirt, "godGrass", 2.0f, "godDirt");
        godStone = new BlockMod("godStone", 2.0f);
        frozenDirt = new BlockMod(EnumMaterialTypes.DIRT, "frozenDirt", 2.0f);
        frozenGrass = new BlockModGrass(EssenceBlocks.frozenDirt, "frozenGrass", 2.0f, "frozenDirt");
        frozenStone = new BlockMod("frozenStone", 2.0f);
        eucaPortal = new BlockEucaPortal("eucaPortal");
        eucaPortalFrame = new BlockMod("eucaPortalFrame", 3.0f);
        depthsPortal = new BlockDepthsPortal("depthsPortal");
        depthsPortalFrame = new BlockMod("depthsPortalFrame", 3.0f);
        boilPortal = new BlockBoilPortal("boilingPortal");
        boilPortalFrame = new BlockMod("boilingPortalFrame", 3.0f);
        frozenPortal = new BlockFrozenPortal("frozenPortal");
        hotBlock = new BlockMod("hotGround", 2.0f);
        ashBlock = new BlockMod(EnumMaterialTypes.STONE, "ash", "ashBlock");
        fire = (Block)new BlockModFire("fire");
        boilingFire = (Block)new BlockBoilingFire("boilingFire");
        mossyEssenceStone = new BlockMossyEssenceStone("mossyEssenceStone", 2.0f);
        dungeonBrick = (Block)new BlockDungeonBlock("dungeonBrick");
        dungeonCrackedBrick = (Block)new BlockDungeonBlock("dungeonCrackedBrick");
        dungeonChisledBrick = (Block)new BlockDungeonBlock("dungeonChiseledBrick");
        dungeonBrickCarved = (Block)new BlockDungeonBlock("dungeonBrickCarved");
        dungeonLamp = (Block)new BlockDungeonBlock("dungeonLamp", true);
        dungeonBrickStairs = (Block)new BlockModStairs(EssenceBlocks.dungeonBrick, "dungeonBrickStairs");
        dungeonCrackedBrickStairs = (Block)new BlockModStairs(EssenceBlocks.dungeonCrackedBrick, "dungeonCrackedBrickStairs");
        dungeonChisledBrickStairs = (Block)new BlockModStairs(EssenceBlocks.dungeonChisledBrick, "dungeonChiseledBrickStairs");
        dungeonBrickCarvedStairs = (Block)new BlockModStairs(EssenceBlocks.dungeonBrickCarved, "dungeonBrickCarvedStairs");
        dungeonLampStairs = (Block)new BlockModStairs(EssenceBlocks.dungeonLamp, "dungeonLampStairs", true);
        dungeonBrickFence = (Block)new BlockModFence(EssenceBlocks.dungeonBrick, "dungeonBrick");
        dungeonCrackedBrickFence = (Block)new BlockModFence(EssenceBlocks.dungeonCrackedBrick, "dungeonCrackedBrick");
        dungeonChisledBrickFence = (Block)new BlockModFence(EssenceBlocks.dungeonChisledBrick, "dungeonChiseledBrick");
        dungeonBrickCarvedFence = (Block)new BlockModFence(EssenceBlocks.dungeonBrickCarved, "dungeonBrickCarved");
        dungeonLampFence = (Block)new BlockModFence(EssenceBlocks.dungeonLamp, "dungeonLamp", true);
        hotBrick = new BlockMod("hotBrick", 2.0f);
        hotBrick_fence = (Block)new BlockModFence(EssenceBlocks.hotBrick, "hotBrick");
        hotBrick_stairs = (Block)new BlockModStairs(EssenceBlocks.hotBrick, "hotBrickStairs");
        hotGlass = (Block)new BlockJoinedGlass("hotGlass");
        smoothGlass = (Block)new BlockJoinedGlass("smoothGlass");
        hotGlassPane = (Block)new BlockJoinedPane("hotGlass");
        smoothGlassPane = (Block)new BlockJoinedPane("smoothGlass");
        witheringBeastStatue = (Block)new BlockStatue("witheringBeastStatue", (ModelStatue)new ModelWitheringBeastStatue(), EnumSounds.WITHER);
        netherBeastStatue = (Block)new BlockStatue("netherBeastStatue", (ModelStatue)new ModelNetherBeastStatue(), EnumSounds.NETHER_BEAST);
        calciaStatue = (Block)new BlockStatue("calciaStatue", (ModelStatue)new ModelCalciaStatue(), EnumSounds.CALCIA);
        eudorStatue = (Block)new BlockStatue("eudorStatue", (ModelStatue)new ModelEudorStatue(), EnumSounds.CALCIA);
        enrichedEnchantmentTable = (Block)new BlockEnrichedEnchantmentTable("enrichedEnchantmentTable");
        hotDoor = new BlockModDoor("hotDoorBlock", 5.0f, null);
        colouredBricks = (Block)new BlockColouredBricks();
        miniColouredBricks = (Block)new BlockMiniColouredBricks();
        glowshroom = (Block)new BlockGlowshroom("glowshroom");
        caveVine = (Block)new BlockCaveVine("caveVine");
        storageBlocks = (Block)new BlockStorageBlocks();
        storageBlocks1 = (Block)new BlockStorageBlocks1();
        storageBlocks2 = (Block)new BlockStorageBlocks2();
        storageBlocks3 = (Block)new BlockStorageBlocks3();
        christmasLights = (Block)new BlockChristmasLights("christmasLights");
        workshopCarpet = new BlockMod(EnumMaterialTypes.WOOL, "workshopCarpet", 0.5f);
        frozenGlass = (Block)new BlockJoinedGlass("frozenGlass");
        frozenPane = (Block)new BlockJoinedPane("frozenGlass");
        workshopLamp = new BlockMod(EnumMaterialTypes.GLASS, "workshopLamp", 0.5f).setLightLevel(1.0f);
        workshopStone = new BlockMod(EnumMaterialTypes.STONE, "workshopStone", 0.5f);
        workshopStoneStair = (Block)new BlockModStairs(EssenceBlocks.workshopStone, "workshopStairs");
        workshopStoneFence = (Block)new BlockModFence(EssenceBlocks.workshopStone, "workshopStone");
        frozenDoor = new BlockModDoor("frozenDoorBlock", 5.0f, null);
        candyCane = new BlockMod(EnumMaterialTypes.WOOD, "candyCane", 2.0f);
        workshopSlab = (Block)new BlockHalfSlab("workshopSlab", EssenceBlocks.workshopStone);
        eucaTallGrass = new BlockModFlower("eucaTallGrass");
        eucaGreenFlower = new BlockModFlower("eucaGreenFlower");
        eucaBlueFlower = new BlockModFlower("eucaBlueFlower");
    }
}
