package net.essence.client.render.mob.model.statue;

import net.minecraft.client.model.*;
import net.minecraft.entity.*;

public class ModelEnderChampionStatue extends ModelStatue
{
    ModelRenderer Chest;
    ModelRenderer Back;
    ModelRenderer Rib1;
    ModelRenderer Rib2;
    ModelRenderer Rib3;
    ModelRenderer Rib4;
    ModelRenderer Rib5;
    ModelRenderer Rib6;
    ModelRenderer Rib7;
    ModelRenderer SomeBone;
    ModelRenderer LeftUpperLegBone;
    ModelRenderer RightUpperLegBone;
    ModelRenderer LeftBackwardKnee;
    ModelRenderer RightBackwardKnee;
    ModelRenderer LeftFoot;
    ModelRenderer RightFoot;
    ModelRenderer LeftLegSpike;
    ModelRenderer RightLegSpike;
    ModelRenderer RightShoulder;
    ModelRenderer LeftShoulder;
    ModelRenderer RightElbow;
    ModelRenderer LeftElbow;
    ModelRenderer LeftArm;
    ModelRenderer RightArm;
    ModelRenderer RightArmSpike;
    ModelRenderer LeftArmSpike;
    ModelRenderer Head;
    ModelRenderer RightShoulderSpikeBase;
    ModelRenderer LeftShoulderSpikeBase;
    ModelRenderer RightSpikeEnd;
    ModelRenderer LeftSpikeEnd;
    ModelRenderer RightShield;
    ModelRenderer LeftShield;
    
    public ModelEnderChampionStatue() {
        this.textureWidth = 128;
        this.textureHeight = 64;
        (this.Chest = new ModelRenderer((ModelBase)this, 0, 0)).addBox(-7.5f, 0.0f, -4.5f, 15, 7, 9);
        this.Chest.setRotationPoint(0.0f, -12.0f, 0.0f);
        this.Chest.setTextureSize(128, 64);
        this.Chest.mirror = true;
        this.setRotation(this.Chest, 0.0f, 0.0f, 0.0f);
        (this.Back = new ModelRenderer((ModelBase)this, 0, 16)).addBox(-1.0f, 0.0f, -1.0f, 2, 12, 2);
        this.Back.setRotationPoint(0.0f, -5.0f, 0.0f);
        this.Back.setTextureSize(128, 64);
        this.Back.mirror = true;
        this.setRotation(this.Back, 0.0f, 0.0f, 0.0f);
        (this.Rib1 = new ModelRenderer((ModelBase)this, 8, 16)).addBox(-2.0f, -0.5f, -0.5f, 4, 1, 1);
        this.Rib1.setRotationPoint(0.0f, -4.0f, 0.0f);
        this.Rib1.setTextureSize(128, 64);
        this.Rib1.mirror = true;
        this.setRotation(this.Rib1, 0.0f, 0.0f, 0.0f);
        (this.Rib2 = new ModelRenderer((ModelBase)this, 8, 18)).addBox(-3.0f, -0.5f, -0.5f, 6, 1, 1);
        this.Rib2.setRotationPoint(0.0f, -2.5f, 0.0f);
        this.Rib2.setTextureSize(128, 64);
        this.Rib2.mirror = true;
        this.setRotation(this.Rib2, 0.0f, 0.0f, 0.0f);
        (this.Rib3 = new ModelRenderer((ModelBase)this, 8, 20)).addBox(-4.0f, -0.5f, -0.5f, 8, 1, 1);
        this.Rib3.setRotationPoint(0.0f, -1.0f, 0.0f);
        this.Rib3.setTextureSize(128, 64);
        this.Rib3.mirror = true;
        this.setRotation(this.Rib3, 0.0f, 0.0f, 0.0f);
        (this.Rib4 = new ModelRenderer((ModelBase)this, 8, 22)).addBox(-5.0f, -0.5f, -0.5f, 10, 1, 1);
        this.Rib4.setRotationPoint(0.0f, 0.5f, 0.0f);
        this.Rib4.setTextureSize(128, 64);
        this.Rib4.mirror = true;
        this.setRotation(this.Rib4, 0.0f, 0.0f, 0.0f);
        (this.Rib5 = new ModelRenderer((ModelBase)this, 8, 20)).addBox(-4.0f, -0.5f, -0.5f, 8, 1, 1);
        this.Rib5.setRotationPoint(0.0f, 2.0f, 0.0f);
        this.Rib5.setTextureSize(128, 64);
        this.Rib5.mirror = true;
        this.setRotation(this.Rib5, 0.0f, 0.0f, 0.0f);
        (this.Rib6 = new ModelRenderer((ModelBase)this, 8, 18)).addBox(-3.0f, -0.5f, -0.5f, 6, 1, 1);
        this.Rib6.setRotationPoint(0.0f, 3.5f, 0.0f);
        this.Rib6.setTextureSize(128, 64);
        this.Rib6.mirror = true;
        this.setRotation(this.Rib6, 0.0f, 0.0f, 0.0f);
        (this.Rib7 = new ModelRenderer((ModelBase)this, 8, 16)).addBox(-2.0f, -0.5f, -0.5f, 4, 1, 1);
        this.Rib7.setRotationPoint(0.0f, 5.0f, 0.0f);
        this.Rib7.setTextureSize(128, 64);
        this.Rib7.mirror = true;
        this.setRotation(this.Rib7, 0.0f, 0.0f, 0.0f);
        (this.SomeBone = new ModelRenderer((ModelBase)this, 8, 24)).addBox(-5.0f, 0.0f, -1.5f, 10, 3, 3);
        this.SomeBone.setRotationPoint(0.0f, 7.0f, 0.0f);
        this.SomeBone.setTextureSize(128, 64);
        this.SomeBone.mirror = true;
        this.setRotation(this.SomeBone, 0.0f, 0.0f, 0.0f);
        (this.LeftUpperLegBone = new ModelRenderer((ModelBase)this, 0, 30)).addBox(-1.0f, -1.0f, -1.0f, 2, 8, 2);
        this.LeftUpperLegBone.setRotationPoint(4.0f, 9.0f, 0.0f);
        this.LeftUpperLegBone.setTextureSize(128, 64);
        this.LeftUpperLegBone.mirror = true;
        this.setRotation(this.LeftUpperLegBone, 0.4537856f, 0.0f, 0.0f);
        (this.RightUpperLegBone = new ModelRenderer((ModelBase)this, 0, 30)).addBox(-1.0f, -1.0f, -1.0f, 2, 8, 2);
        this.RightUpperLegBone.setRotationPoint(-4.0f, 9.0f, 0.0f);
        this.RightUpperLegBone.setTextureSize(128, 64);
        this.RightUpperLegBone.mirror = true;
        this.setRotation(this.RightUpperLegBone, 0.4537856f, 0.0f, 0.0f);
        (this.LeftBackwardKnee = new ModelRenderer((ModelBase)this, 0, 40)).addBox(-1.0f, -1.0f, 0.5f, 2, 9, 2);
        this.LeftBackwardKnee.setRotationPoint(4.0f, 14.0f, 2.0f);
        this.LeftBackwardKnee.setTextureSize(128, 64);
        this.LeftBackwardKnee.mirror = true;
        this.setRotation(this.LeftBackwardKnee, -0.3141593f, 0.0f, 0.0f);
        (this.RightBackwardKnee = new ModelRenderer((ModelBase)this, 0, 40)).addBox(-1.0f, -1.0f, 0.5f, 2, 9, 2);
        this.RightBackwardKnee.setRotationPoint(-4.0f, 14.0f, 2.0f);
        this.RightBackwardKnee.setTextureSize(128, 64);
        this.RightBackwardKnee.mirror = true;
        this.setRotation(this.RightBackwardKnee, -0.3141593f, 0.0f, 0.0f);
        (this.LeftFoot = new ModelRenderer((ModelBase)this, 8, 30)).addBox(-1.0f, 0.0f, -4.0f, 2, 2, 5);
        this.LeftFoot.setRotationPoint(4.0f, 22.0f, 1.0f);
        this.LeftFoot.setTextureSize(128, 64);
        this.LeftFoot.mirror = true;
        this.setRotation(this.LeftFoot, 0.0f, 0.0f, 0.0f);
        (this.RightFoot = new ModelRenderer((ModelBase)this, 8, 30)).addBox(-1.0f, 0.0f, -4.0f, 2, 2, 5);
        this.RightFoot.setRotationPoint(-4.0f, 22.0f, 1.0f);
        this.RightFoot.setTextureSize(128, 64);
        this.RightFoot.mirror = true;
        this.setRotation(this.RightFoot, 0.0f, 0.0f, 0.0f);
        (this.LeftLegSpike = new ModelRenderer((ModelBase)this, 8, 37)).addBox(-0.5f, -4.0f, -0.5f, 1, 5, 1);
        this.LeftLegSpike.setRotationPoint(4.0f, 14.0f, 4.0f);
        this.LeftLegSpike.setTextureSize(128, 64);
        this.LeftLegSpike.mirror = true;
        this.setRotation(this.LeftLegSpike, -0.2792527f, 0.0f, 0.0f);
        (this.RightLegSpike = new ModelRenderer((ModelBase)this, 8, 37)).addBox(-0.5f, -4.0f, -0.5f, 1, 5, 1);
        this.RightLegSpike.setRotationPoint(-4.0f, 14.0f, 4.0f);
        this.RightLegSpike.setTextureSize(128, 64);
        this.RightLegSpike.mirror = true;
        this.setRotation(this.RightLegSpike, -0.2792527f, 0.0f, 0.0f);
        (this.RightShoulder = new ModelRenderer((ModelBase)this, 48, 0)).addBox(-8.0f, -4.0f, -4.0f, 8, 8, 8);
        this.RightShoulder.setRotationPoint(-7.5f, -9.0f, 0.0f);
        this.RightShoulder.setTextureSize(128, 64);
        this.RightShoulder.mirror = true;
        this.setRotation(this.RightShoulder, 0.0f, 0.0f, 0.0f);
        (this.LeftShoulder = new ModelRenderer((ModelBase)this, 48, 0)).addBox(0.0f, -4.0f, -4.0f, 8, 8, 8);
        this.LeftShoulder.setRotationPoint(7.5f, -9.0f, 0.0f);
        this.LeftShoulder.setTextureSize(128, 64);
        this.LeftShoulder.mirror = true;
        this.setRotation(this.LeftShoulder, 0.0f, 0.0f, 0.0f);
        (this.RightElbow = new ModelRenderer((ModelBase)this, 0, 51)).addBox(-1.0f, 0.0f, -1.0f, 2, 9, 2);
        this.RightElbow.setRotationPoint(-12.0f, -6.0f, 0.0f);
        this.RightElbow.setTextureSize(128, 64);
        this.RightElbow.mirror = true;
        this.setRotation(this.RightElbow, 0.5235988f, 0.0f, 0.0f);
        (this.LeftElbow = new ModelRenderer((ModelBase)this, 0, 51)).addBox(-1.0f, 0.0f, -1.0f, 2, 9, 2);
        this.LeftElbow.setRotationPoint(12.0f, -6.0f, 0.0f);
        this.LeftElbow.setTextureSize(128, 64);
        this.LeftElbow.mirror = true;
        this.setRotation(this.LeftElbow, 0.5235988f, 0.0f, 0.0f);
        (this.LeftArm = new ModelRenderer((ModelBase)this, 8, 43)).addBox(-1.0f, -1.0f, -1.0f, 2, 14, 2);
        this.LeftArm.setRotationPoint(12.0f, 1.0f, 5.0f);
        this.LeftArm.setTextureSize(128, 64);
        this.LeftArm.mirror = true;
        this.setRotation(this.LeftArm, -0.6632251f, 0.0f, 0.0f);
        (this.RightArm = new ModelRenderer((ModelBase)this, 8, 43)).addBox(-1.0f, -1.0f, -1.0f, 2, 14, 2);
        this.RightArm.setRotationPoint(-12.0f, 1.0f, 5.0f);
        this.RightArm.setTextureSize(128, 64);
        this.RightArm.mirror = true;
        this.setRotation(this.RightArm, -0.6632251f, 0.0f, 0.0f);
        (this.RightArmSpike = new ModelRenderer((ModelBase)this, 16, 43)).addBox(0.0f, 0.0f, -1.0f, 1, 7, 1);
        this.RightArmSpike.setRotationPoint(-12.0f, 1.0f, 5.0f);
        this.RightArmSpike.setTextureSize(128, 64);
        this.RightArmSpike.mirror = true;
        this.setRotation(this.RightArmSpike, 2.844887f, 0.0f, 0.0f);
        (this.LeftArmSpike = new ModelRenderer((ModelBase)this, 16, 43)).addBox(0.0f, 0.0f, -1.0f, 1, 7, 1);
        this.LeftArmSpike.setRotationPoint(12.0f, 1.0f, 5.0f);
        this.LeftArmSpike.setTextureSize(128, 64);
        this.LeftArmSpike.mirror = true;
        this.setRotation(this.LeftArmSpike, 2.844887f, 0.0f, 0.0f);
        (this.Head = new ModelRenderer((ModelBase)this, 80, 0)).addBox(-3.0f, -6.0f, -3.0f, 6, 6, 6);
        this.Head.setRotationPoint(0.0f, -12.0f, 0.0f);
        this.Head.setTextureSize(128, 64);
        this.Head.mirror = true;
        this.setRotation(this.Head, 0.0f, 0.0f, 0.0f);
        (this.RightShoulderSpikeBase = new ModelRenderer((ModelBase)this, 34, 16)).addBox(-1.0f, -6.0f, -1.0f, 2, 7, 2);
        this.RightShoulderSpikeBase.setRotationPoint(-12.0f, -13.0f, 0.0f);
        this.RightShoulderSpikeBase.setTextureSize(128, 64);
        this.RightShoulderSpikeBase.mirror = true;
        this.setRotation(this.RightShoulderSpikeBase, 0.0f, 0.0f, -0.3490659f);
        (this.LeftShoulderSpikeBase = new ModelRenderer((ModelBase)this, 34, 16)).addBox(-1.0f, -6.0f, -1.0f, 2, 7, 2);
        this.LeftShoulderSpikeBase.setRotationPoint(12.0f, -13.0f, 0.0f);
        this.LeftShoulderSpikeBase.setTextureSize(128, 64);
        this.LeftShoulderSpikeBase.mirror = true;
        this.setRotation(this.LeftShoulderSpikeBase, 0.0f, 0.0f, 0.3490659f);
        (this.RightSpikeEnd = new ModelRenderer((ModelBase)this, 42, 16)).addBox(-0.5f, -7.0f, -0.5f, 1, 7, 1);
        this.RightSpikeEnd.setRotationPoint(-14.0f, -18.0f, 0.0f);
        this.RightSpikeEnd.setTextureSize(128, 64);
        this.RightSpikeEnd.mirror = true;
        this.setRotation(this.RightSpikeEnd, 0.0f, 0.0f, 0.6632251f);
        (this.LeftSpikeEnd = new ModelRenderer((ModelBase)this, 42, 16)).addBox(-0.5f, -7.0f, -0.5f, 1, 7, 1);
        this.LeftSpikeEnd.setRotationPoint(14.0f, -18.0f, 0.0f);
        this.LeftSpikeEnd.setTextureSize(128, 64);
        this.LeftSpikeEnd.mirror = true;
        this.setRotation(this.LeftSpikeEnd, 0.0f, 0.0f, -0.6632251f);
        (this.RightShield = new ModelRenderer((ModelBase)this, 104, 0)).addBox(-1.0f, -4.5f, -4.5f, 1, 9, 9);
        this.RightShield.setRotationPoint(-13.0f, 7.0f, 0.0f);
        this.RightShield.setTextureSize(128, 64);
        this.RightShield.mirror = true;
        this.setRotation(this.RightShield, -0.6632251f, 0.0f, 0.0f);
        (this.LeftShield = new ModelRenderer((ModelBase)this, 104, 0)).addBox(0.0f, -4.5f, -4.5f, 1, 9, 9);
        this.LeftShield.setRotationPoint(13.0f, 7.0f, 0.0f);
        this.LeftShield.setTextureSize(128, 64);
        this.LeftShield.mirror = true;
        this.setRotation(this.LeftShield, -0.6632251f, 0.0f, 0.0f);
    }
    
    public void render(final Entity entity, final float f, final float f1, final float f2, final float f3, final float f4, final float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        this.Chest.render(f5);
        this.Back.render(f5);
        this.Rib1.render(f5);
        this.Rib2.render(f5);
        this.Rib3.render(f5);
        this.Rib4.render(f5);
        this.Rib5.render(f5);
        this.Rib6.render(f5);
        this.Rib7.render(f5);
        this.SomeBone.render(f5);
        this.LeftUpperLegBone.render(f5);
        this.RightUpperLegBone.render(f5);
        this.LeftBackwardKnee.render(f5);
        this.RightBackwardKnee.render(f5);
        this.LeftFoot.render(f5);
        this.RightFoot.render(f5);
        this.LeftLegSpike.render(f5);
        this.RightLegSpike.render(f5);
        this.RightShoulder.render(f5);
        this.LeftShoulder.render(f5);
        this.RightElbow.render(f5);
        this.LeftElbow.render(f5);
        this.LeftArm.render(f5);
        this.RightArm.render(f5);
        this.RightArmSpike.render(f5);
        this.LeftArmSpike.render(f5);
        this.Head.render(f5);
        this.RightShoulderSpikeBase.render(f5);
        this.LeftShoulderSpikeBase.render(f5);
        this.RightSpikeEnd.render(f5);
        this.LeftSpikeEnd.render(f5);
        this.RightShield.render(f5);
        this.LeftShield.render(f5);
    }
    
    @Override
    public void render(final float f5) {
        this.Chest.render(f5);
        this.Back.render(f5);
        this.Rib1.render(f5);
        this.Rib2.render(f5);
        this.Rib3.render(f5);
        this.Rib4.render(f5);
        this.Rib5.render(f5);
        this.Rib6.render(f5);
        this.Rib7.render(f5);
        this.SomeBone.render(f5);
        this.LeftUpperLegBone.render(f5);
        this.RightUpperLegBone.render(f5);
        this.LeftBackwardKnee.render(f5);
        this.RightBackwardKnee.render(f5);
        this.LeftFoot.render(f5);
        this.RightFoot.render(f5);
        this.LeftLegSpike.render(f5);
        this.RightLegSpike.render(f5);
        this.RightShoulder.render(f5);
        this.LeftShoulder.render(f5);
        this.RightElbow.render(f5);
        this.LeftElbow.render(f5);
        this.LeftArm.render(f5);
        this.RightArm.render(f5);
        this.RightArmSpike.render(f5);
        this.LeftArmSpike.render(f5);
        this.Head.render(f5);
        this.RightShoulderSpikeBase.render(f5);
        this.LeftShoulderSpikeBase.render(f5);
        this.RightSpikeEnd.render(f5);
        this.LeftSpikeEnd.render(f5);
        this.RightShield.render(f5);
        this.LeftShield.render(f5);
    }
    
    public void setRotationAngles(final float f, final float f1, final float f2, final float f3, final float f4, final float f5, final Entity e) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
    }
}
