package net.essence.entity;

public class MobStats
{
    public static double normalSpeed;
    public static double follow;
    public static double knockBackResistance;
    public static final int witheringBeastBossID = 0;
    public static final int netherBeastBossID = 1;
    public static final int calciaBossID = 2;
    public static final int wraithBossID = 3;
    public static final int eudorBossID = 4;
    public static double spyclopsHealth;
    public static double spyclopsDamage;
    public static double spyclopsSpeed;
    public static double spyclopsFollowRange;
    public static double robotHealth;
    public static double robotDamage;
    public static double robotSpeed;
    public static double robotFollowRange;
    public static double boomHealth;
    public static double boomSpeed;
    public static double boomFollowRange;
    public static double bigHongoHealth;
    public static double bigHongoDamage;
    public static double bigHongoSpeed;
    public static double bigHongoFollowRange;
    public static double mediumHongoHealth;
    public static double mediumHongoDamage;
    public static double mediumHongoSpeed;
    public static double mediumHongoFollowRange;
    public static double smallHongoHealth;
    public static double smallHongoDamage;
    public static double smallHongoSpeed;
    public static double smallHongoFollowRange;
    public static double reaperHealth;
    public static double reaperDamage;
    public static double reaperSpeed;
    public static double reaperFollowRange;
    public static double bunnyHealth;
    public static double bunnyDamage;
    public static double bunnySpeed;
    public static double bunnyFollowRange;
    public static double sandCrawlerHealth;
    public static double sandCrawlerDamage;
    public static double sandCrawlerSpeed;
    public static double sandCrawlerFollowRange;
    public static double turtleHealth;
    public static double turtleDamage;
    public static double turtleSpeed;
    public static double turtleFollowRange;
    public static double fishHealth;
    public static double fishSpeed;
    public static double fishFollowRange;
    public static double magmaGiantHealth;
    public static double magmaGiantDamage;
    public static double magmaGiantSpeed;
    public static double magmaGiantFollowRange;
    public static double magmaBlazeHealth;
    public static double magmaBlazeDamage;
    public static double crispHealth;
    public static double crispDamage;
    public static double crispSpeed;
    public static double crispFollowRange;
    public static double burntMinerHealth;
    public static double burntMinerDamage;
    public static double burntMinerSpeed;
    public static double burntMinerFollowRange;
    public static double exposedFlameHealth;
    public static double exposedFlameDamage;
    public static double exposedFlameSpeed;
    public static double exposedFlameFollowRange;
    public static double burningLightHealth;
    public static double burningLightDamage;
    public static double burningLightSpeed;
    public static double burningLightFollowRange;
    public static double ashHoarderHealth;
    public static double ashHoarderDamage;
    public static double ashHoarderSpeed;
    public static double ashHoarderFollowRange;
    public static double burntAshHealth;
    public static double burntAshDamage;
    public static double burntAshSpeed;
    public static double burntAshFollowRange;
    public static double insectoHealth;
    public static double insectoDamage;
    public static double insectoSpeed;
    public static double insectoFollowRange;
    public static double psyollomHealth;
    public static double psyollomDamage;
    public static double psyollomSpeed;
    public static double psyollomFollowRange;
    public static double eucaHopperHealth;
    public static double eucaHopperHealthTamed;
    public static double eucaHopperDamage;
    public static double eucaHopperSpeed;
    public static double eucaHopperFollowRange;
    public static double eucaFighterHealth;
    public static double eucaFighterDamage;
    public static double eucaFighterSpeed;
    public static double eucaFighterFollowRange;
    public static double eucaChargerHealth;
    public static double eucaChargerDamage;
    public static double eucaChargerSpeed;
    public static double eucaChargerFollowRange;
    public static double depthsBeastHealth;
    public static double depthsBeastDamage;
    public static double depthsBeastSpeed;
    public static double depthsBeastFollowRange;
    public static double spikedBeastHealth;
    public static double spikedBeastDamage;
    public static double spikedBeastSpeed;
    public static double spikedBeastFollowRange;
    public static double darknessCrawlerHealth;
    public static double darknessCrawlerDamage;
    public static double darknessCrawlerSpeed;
    public static double darknessCrawlerFollowRange;
    public static double depthsHunterHealth;
    public static double depthsHunterDamage;
    public static double depthsHunterSpeed;
    public static double depthsHunterFollowRange;
    public static double witheringBeastHealth;
    public static double witheringBeastDamage;
    public static double witheringBeastSpeed;
    public static double witheringBeastFollowRange;
    public static double netherBeastHealth;
    public static double netherBeastDamage;
    public static double netherBeastSpeed;
    public static double netherBeastFollowRange;
    public static double calciaHealth;
    public static double calciaDamage;
    public static double calciaSpeed;
    public static double calciaFollowRange;
    public static double eudorHealth;
    public static double eudorDamage;
    public static double eudorSpeed;
    public static double eudorFollowRange;
    public static double wraithHealth;
    public static double wraithDamage;
    public static double wraithSpeed;
    public static double wraithFollowRange;
    
    static {
        MobStats.normalSpeed = 0.350000011920929;
        MobStats.follow = 30.0;
        MobStats.knockBackResistance = 0.0;
        MobStats.spyclopsHealth = 20.0;
        MobStats.spyclopsDamage = 5.0;
        MobStats.spyclopsSpeed = MobStats.normalSpeed;
        MobStats.spyclopsFollowRange = MobStats.follow;
        MobStats.robotHealth = 25.0;
        MobStats.robotDamage = 4.0;
        MobStats.robotSpeed = MobStats.normalSpeed;
        MobStats.robotFollowRange = MobStats.follow;
        MobStats.boomHealth = 16.0;
        MobStats.boomSpeed = MobStats.normalSpeed;
        MobStats.boomFollowRange = MobStats.follow;
        MobStats.bigHongoHealth = 30.0;
        MobStats.bigHongoDamage = 6.0;
        MobStats.bigHongoSpeed = MobStats.normalSpeed;
        MobStats.bigHongoFollowRange = MobStats.follow;
        MobStats.mediumHongoHealth = 20.0;
        MobStats.mediumHongoDamage = 5.0;
        MobStats.mediumHongoSpeed = MobStats.normalSpeed;
        MobStats.mediumHongoFollowRange = MobStats.follow;
        MobStats.smallHongoHealth = 10.0;
        MobStats.smallHongoDamage = 3.0;
        MobStats.smallHongoSpeed = MobStats.normalSpeed;
        MobStats.smallHongoFollowRange = MobStats.follow;
        MobStats.reaperHealth = 50.0;
        MobStats.reaperDamage = 8.0;
        MobStats.reaperSpeed = MobStats.normalSpeed;
        MobStats.reaperFollowRange = MobStats.follow;
        MobStats.bunnyHealth = 5.0;
        MobStats.bunnyDamage = 3.0;
        MobStats.bunnySpeed = MobStats.normalSpeed;
        MobStats.bunnyFollowRange = MobStats.follow;
        MobStats.sandCrawlerHealth = 35.0;
        MobStats.sandCrawlerDamage = 8.0;
        MobStats.sandCrawlerSpeed = MobStats.normalSpeed;
        MobStats.sandCrawlerFollowRange = MobStats.follow;
        MobStats.turtleHealth = 10.0;
        MobStats.turtleDamage = 3.0;
        MobStats.turtleSpeed = MobStats.normalSpeed;
        MobStats.turtleFollowRange = MobStats.follow;
        MobStats.fishHealth = 2.0;
        MobStats.fishSpeed = MobStats.normalSpeed;
        MobStats.fishFollowRange = MobStats.follow;
        MobStats.magmaGiantHealth = 50.0;
        MobStats.magmaGiantDamage = 9.0;
        MobStats.magmaGiantSpeed = MobStats.normalSpeed;
        MobStats.magmaGiantFollowRange = MobStats.follow;
        MobStats.magmaBlazeHealth = 35.0;
        MobStats.magmaBlazeDamage = 5.0;
        MobStats.crispHealth = 50.0;
        MobStats.crispDamage = 8.0;
        MobStats.crispSpeed = MobStats.normalSpeed;
        MobStats.crispFollowRange = MobStats.follow;
        MobStats.burntMinerHealth = 40.0;
        MobStats.burntMinerDamage = 7.0;
        MobStats.burntMinerSpeed = MobStats.normalSpeed;
        MobStats.burntMinerFollowRange = MobStats.follow;
        MobStats.exposedFlameHealth = 30.0;
        MobStats.exposedFlameDamage = 8.0;
        MobStats.exposedFlameSpeed = MobStats.normalSpeed;
        MobStats.exposedFlameFollowRange = MobStats.follow;
        MobStats.burningLightHealth = 30.0;
        MobStats.burningLightDamage = 8.0;
        MobStats.burningLightSpeed = MobStats.normalSpeed;
        MobStats.burningLightFollowRange = MobStats.follow;
        MobStats.ashHoarderHealth = 40.0;
        MobStats.ashHoarderDamage = 8.0;
        MobStats.ashHoarderSpeed = MobStats.normalSpeed;
        MobStats.ashHoarderFollowRange = MobStats.follow;
        MobStats.burntAshHealth = 40.0;
        MobStats.burntAshDamage = 8.0;
        MobStats.burntAshSpeed = MobStats.normalSpeed;
        MobStats.burntAshFollowRange = MobStats.follow;
        MobStats.insectoHealth = 25.0;
        MobStats.insectoDamage = 10.0;
        MobStats.insectoSpeed = MobStats.normalSpeed;
        MobStats.insectoFollowRange = MobStats.follow;
        MobStats.psyollomHealth = 50.0;
        MobStats.psyollomDamage = 10.0;
        MobStats.psyollomSpeed = MobStats.normalSpeed;
        MobStats.psyollomFollowRange = MobStats.follow;
        MobStats.eucaHopperHealth = 30.0;
        MobStats.eucaHopperHealthTamed = 50.0;
        MobStats.eucaHopperDamage = 8.0;
        MobStats.eucaHopperSpeed = MobStats.normalSpeed;
        MobStats.eucaHopperFollowRange = MobStats.follow;
        MobStats.eucaFighterHealth = 50.0;
        MobStats.eucaFighterDamage = 7.0;
        MobStats.eucaFighterSpeed = MobStats.normalSpeed;
        MobStats.eucaFighterFollowRange = MobStats.follow;
        MobStats.eucaChargerHealth = 50.0;
        MobStats.eucaChargerDamage = 7.0;
        MobStats.eucaChargerSpeed = MobStats.normalSpeed;
        MobStats.eucaChargerFollowRange = MobStats.follow;
        MobStats.depthsBeastHealth = 80.0;
        MobStats.depthsBeastDamage = 10.0;
        MobStats.depthsBeastSpeed = MobStats.normalSpeed;
        MobStats.depthsBeastFollowRange = MobStats.follow;
        MobStats.spikedBeastHealth = 70.0;
        MobStats.spikedBeastDamage = 12.0;
        MobStats.spikedBeastSpeed = MobStats.normalSpeed;
        MobStats.spikedBeastFollowRange = MobStats.follow;
        MobStats.darknessCrawlerHealth = 80.0;
        MobStats.darknessCrawlerDamage = 10.0;
        MobStats.darknessCrawlerSpeed = MobStats.normalSpeed;
        MobStats.darknessCrawlerFollowRange = MobStats.follow;
        MobStats.depthsHunterHealth = 75.0;
        MobStats.depthsHunterDamage = 13.0;
        MobStats.depthsHunterSpeed = MobStats.normalSpeed;
        MobStats.depthsHunterFollowRange = MobStats.follow;
        MobStats.witheringBeastHealth = 250.0;
        MobStats.witheringBeastDamage = 10.0;
        MobStats.witheringBeastSpeed = MobStats.normalSpeed;
        MobStats.witheringBeastFollowRange = MobStats.follow;
        MobStats.netherBeastHealth = 250.0;
        MobStats.netherBeastDamage = 10.0;
        MobStats.netherBeastSpeed = MobStats.normalSpeed;
        MobStats.netherBeastFollowRange = MobStats.follow;
        MobStats.calciaHealth = 250.0;
        MobStats.calciaDamage = 10.0;
        MobStats.calciaSpeed = MobStats.normalSpeed;
        MobStats.calciaFollowRange = MobStats.follow;
        MobStats.eudorHealth = 250.0;
        MobStats.eudorDamage = 10.0;
        MobStats.eudorSpeed = MobStats.normalSpeed;
        MobStats.eudorFollowRange = MobStats.follow;
        MobStats.wraithHealth = 50.0;
        MobStats.wraithDamage = 10.0;
        MobStats.wraithSpeed = MobStats.normalSpeed;
        MobStats.wraithFollowRange = MobStats.follow;
    }
}
